site_name: 佛经集
strict: false
# remote_name: main
theme:
  name: material
  language: 'zh'
  logo: 'fo.svg'
  favicon: 'favicon.ico'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - navigation.top
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 暗

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 明
extra_css:
  - '_static/css/extra.css'
nav:
 - 心经: xinjing/xinjing.md
 - 法华经:
     - 卷一:
       - 序品第一: fahuajing/1.md
       - 方便品第二: fahuajing/2.md
     - 卷二:
       - 譬喻品第三: fahuajing/3.md
       - 信解品第四: fahuajing/4.md
     - 卷三:
       - 药草喻品第五: fahuajing/5.md
       - 授记品第六: fahuajing/6.md
       - 化城喻品第七: fahuajing/7.md
     - 卷四:
       - 五百弟子受记品第八: fahuajing/8.md
       - 授学无学人记品第九: fahuajing/9.md
       - 法师品第十: fahuajing/10.md
       - 见宝塔品第十一: fahuajing/11.md
       - 提婆达多品第十二: fahuajing/12.md
       - 劝持品第十三: fahuajing/13.md
     - 卷五:
       - 安乐行品第十四: fahuajing/14.md
       - 从地涌出品第十五: fahuajing/15.md
       - 如来寿量品第十六: fahuajing/16.md
       - 分别功德品第十七: fahuajing/17.md
     - 卷六:
       - 随喜功德品第十八: fahuajing/18.md
       - 法师功德品第十九: fahuajing/19.md
       - 常不轻菩萨品第二十: fahuajing/20.md
       - 如来神力品第二十一: fahuajing/21.md
       - 嘱累品第二十二: fahuajing/22.md
       - 药王菩萨本事品第二十三: fahuajing/23.md
     - 卷七:
       - 妙音菩萨品第二十四: fahuajing/24.md
       - 观世音菩萨普门品第二十五: fahuajing/25.md
       - 陀罗尼品第二十六: fahuajing/26.md
       - 妙庄严王本事品第二十七: fahuajing/27.md
       - 普贤菩萨劝发品第二十八: fahuajing/28.md
 - 楞严经:
     - 卷一: lengyanjing/1.md
     - 卷二: lengyanjing/2.md
     - 卷三: lengyanjing/3.md
     - 卷四: lengyanjing/4.md
     - 卷五: lengyanjing/5.md
     - 卷六: lengyanjing/6.md
     - 卷七: lengyanjing/7.md
     - 卷八: lengyanjing/8.md
     - 卷九: lengyanjing/9.md
     - 卷十: lengyanjing/10.md
 - 佛说阿弥陀经: amituojing/1.md
 - 金刚经: jingangjing/1.md
 - 药师经: yaoshijing/1.md
 - 地藏菩萨本愿经:
     - 地藏菩萨本愿经卷上:
       - 忉利天宫神通品第一: dizangjing/1.md
       - 分身集会品第二: dizangjing/2.md
       - 观众生业缘品第三: dizangjing/3.md
       - 阎浮众生业感品第四: dizangjing/4.md
     - 地藏菩萨本愿经卷上:
       - 地狱名号品第五: dizangjing/5.md
       - 如来赞叹品第六: dizangjing/6.md
       - 利益存亡品第七: dizangjing/7.md
       - 阎罗王众赞叹品第八: dizangjing/8.md
       - 称佛名号品第九: dizangjing/9.md
     - 地藏菩萨本愿经卷上:
       - 校量布施功德缘品第十: dizangjing/10.md
       - 地神护法品第十一: dizangjing/11.md
       - 见闻利益品第十二: dizangjing/12.md
       - 嘱累人天品第十三: dizangjing/13.md
 - 华严经:
     - 世主妙严品第一:
       - 之一: huayanjing/1.md
       - 之二: huayanjing/2.md
       - 之三: huayanjing/3.md
       - 之四: huayanjing/4.md
       - 之五: huayanjing/5.md
     - 如来现相品: huayanjing/6.md
     - 普贤三昧品: huayanjing/7.md
     - 世界成就品: huayanjing/8.md
     - 华藏世界品第五:
       - 之一: huayanjing/9.md
       - 之二: huayanjing/10.md
       - 之三: huayanjing/11.md
     - 毗卢遮那品第六: huayanjing/12.md
     - 如来名号品第七: huayanjing/13.md
     - 四圣谛品第八: huayanjing/14.md
     - 光明觉品第九: huayanjing/15.md
     - 菩萨问明品第十: huayanjing/16.md
     - 净行品第十一: huayanjing/17.md
     - 贤首品第十二:
       - 之一: huayanjing/18.md
       - 之二: huayanjing/19.md
     - 升须弥山顶品第十三: huayanjing/20.md
     - 须弥顶上偈赞第十四: huayanjing/21.md
     - 十住第十五: huayanjing/22.md
       
