site_name: 佛经集
strict: false
# remote_name: main
theme:
  name: material
  language: 'zh'
  logo: 'fo.svg'
  favicon: 'favicon.ico'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - navigation.top
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 暗

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 明
extra_css:
  - '_static/css/extra.css'
nav:
 - 阿含部类:
   - 长阿含经: 
     - 长阿含经序: ahanbu/changahanjing/1.md
     - 佛说长阿含经卷第一:
       - 第一分初大本经第一: ahanbu/changahanjing/2.md
     - 佛说长阿含经卷第二:
       - 第一分游行经第二初: ahanbu/changahanjing/3.md
     - 佛说长阿含经卷第三:
       - 游行经第二中: ahanbu/changahanjing/4.md
     - 佛说长阿含经卷第四:
       - 游行经第二后: ahanbu/changahanjing/5.md
     - 佛说长阿含经卷第五:
       - 第一分典尊经第三: ahanbu/changahanjing/6.md
       - 第一分阇尼沙经第四: ahanbu/changahanjing/7.md
     - 佛说长阿含经卷第六:
       - 第二分初小缘经第一: ahanbu/changahanjing/8.md
       - 佛说长阿含第二分转轮圣王修行经第二: ahanbu/changahanjing/9.md
     - 佛说长阿含经卷第七:
       - 第二分弊宿经第三: ahanbu/changahanjing/10.md
     - 佛说长阿含经卷第八:
       - 第二分散陀那经第四: ahanbu/changahanjing/11.md
       - 佛说长阿含第二分众集经第五: ahanbu/changahanjing/12.md
     - 佛说长阿含经卷第九:
       - 第二分十上经第六: ahanbu/changahanjing/13.md
       - 佛说长阿含第二分增一经第七: ahanbu/changahanjing/14.md
     - 佛说长阿含经卷第十:
       - 第二分三聚经第八: ahanbu/changahanjing/15.md
       - 佛说长阿含第二分大缘方便经第九: ahanbu/changahanjing/16.md
       - 佛说长阿含第二分释提桓因问经第十: ahanbu/changahanjing/17.md
     - 佛说长阿含经卷第十一:
       - 第二分阿㝹夷经第十一: ahanbu/changahanjing/18.md
       - 佛说长阿含第二分善生经第十二: ahanbu/changahanjing/19.md
     - 佛说长阿含经卷第十二:
       - 第二分清净经第十三: ahanbu/changahanjing/20.md
       - 佛说长阿含第二分自欢喜经第十四: ahanbu/changahanjing/21.md
       - 佛说长阿含第二分大会经第十五: ahanbu/changahanjing/22.md
     - 佛说长阿含经卷第十三:
       - 第三分阿摩昼经第一: ahanbu/changahanjing/23.md
     - 佛说长阿含经卷第十四:
       - 第三分梵动经第二: ahanbu/changahanjing/24.md
     - 佛说长阿含经卷第十五:
       - 第三分种德经第三: ahanbu/changahanjing/25.md
       - 佛说长阿含第三分究罗檀头经第四: ahanbu/changahanjing/26.md
     - 佛说长阿含经卷第十六:
       - 第三分坚固经第五: ahanbu/changahanjing/27.md
       - 佛说长阿含第三分裸形梵志经第六: ahanbu/changahanjing/28.md
       - 佛说长阿含第三分三明经第七: ahanbu/changahanjing/29.md
     - 佛说长阿含经卷第十七:
       - 第三分沙门果经第八: ahanbu/changahanjing/30.md
       - 佛说长阿含第三分布吒婆楼经第九: ahanbu/changahanjing/31.md
       - 佛说长阿含第三分露遮经第十: ahanbu/changahanjing/32.md
     - 佛说长阿含经卷第十八:
       - 第四分世记经阎浮提州品第一: ahanbu/changahanjing/33.md
       - 第四分世记经郁单曰品第二: ahanbu/changahanjing/34.md
       - 第四分世记经转轮圣王品第三: ahanbu/changahanjing/35.md
     - 佛说长阿含经卷第十九:
       - 第四分世记经地狱品第四: ahanbu/changahanjing/36.md
       - 第四分世记经龙鸟品第五: ahanbu/changahanjing/37.md
     - 佛说长阿含经卷第二十:
       - 第四分世记经阿须伦品第六: ahanbu/changahanjing/38.md
       - 第四分世记经四天王品第七: ahanbu/changahanjing/39.md
       - 第四分世记经忉利天品第八: ahanbu/changahanjing/40.md
     - 佛说长阿含经卷第二十一:
       - 第四分世记经三灾品第九: ahanbu/changahanjing/41.md
       - 第四分世记经战斗品第十: ahanbu/changahanjing/42.md
     - 佛说长阿含经卷第二十二:
       - 第四分世记经三中劫品第十一: ahanbu/changahanjing/43.md
       - 第四分世记经世本缘品第十二: ahanbu/changahanjing/44.md
   - 杂阿含经:
      - 卷第一: ahanbu/zaahanjing/1.md
 - 心经: xinjing/xinjing.md
 - 法华经:
     - 卷一:
       - 序品第一: fahuajing/1.md
       - 方便品第二: fahuajing/2.md
     - 卷二:
       - 譬喻品第三: fahuajing/3.md
       - 信解品第四: fahuajing/4.md
     - 卷三:
       - 药草喻品第五: fahuajing/5.md
       - 授记品第六: fahuajing/6.md
       - 化城喻品第七: fahuajing/7.md
     - 卷四:
       - 五百弟子受记品第八: fahuajing/8.md
       - 授学无学人记品第九: fahuajing/9.md
       - 法师品第十: fahuajing/10.md
       - 见宝塔品第十一: fahuajing/11.md
       - 提婆达多品第十二: fahuajing/12.md
       - 劝持品第十三: fahuajing/13.md
     - 卷五:
       - 安乐行品第十四: fahuajing/14.md
       - 从地涌出品第十五: fahuajing/15.md
       - 如来寿量品第十六: fahuajing/16.md
       - 分别功德品第十七: fahuajing/17.md
     - 卷六:
       - 随喜功德品第十八: fahuajing/18.md
       - 法师功德品第十九: fahuajing/19.md
       - 常不轻菩萨品第二十: fahuajing/20.md
       - 如来神力品第二十一: fahuajing/21.md
       - 嘱累品第二十二: fahuajing/22.md
       - 药王菩萨本事品第二十三: fahuajing/23.md
     - 卷七:
       - 妙音菩萨品第二十四: fahuajing/24.md
       - 观世音菩萨普门品第二十五: fahuajing/25.md
       - 陀罗尼品第二十六: fahuajing/26.md
       - 妙庄严王本事品第二十七: fahuajing/27.md
       - 普贤菩萨劝发品第二十八: fahuajing/28.md
 - 楞严经:
     - 卷一: lengyanjing/1.md
     - 卷二: lengyanjing/2.md
     - 卷三: lengyanjing/3.md
     - 卷四: lengyanjing/4.md
     - 卷五: lengyanjing/5.md
     - 卷六: lengyanjing/6.md
     - 卷七: lengyanjing/7.md
     - 卷八: lengyanjing/8.md
     - 卷九: lengyanjing/9.md
     - 卷十: lengyanjing/10.md
 - 佛说阿弥陀经: amituojing/1.md
 - 金刚经: jingangjing/1.md
 - 药师经: yaoshijing/1.md
 - 地藏菩萨本愿经:
     - 地藏菩萨本愿经卷上:
       - 忉利天宫神通品第一: dizangjing/1.md
       - 分身集会品第二: dizangjing/2.md
       - 观众生业缘品第三: dizangjing/3.md
       - 阎浮众生业感品第四: dizangjing/4.md
     - 地藏菩萨本愿经卷上:
       - 地狱名号品第五: dizangjing/5.md
       - 如来赞叹品第六: dizangjing/6.md
       - 利益存亡品第七: dizangjing/7.md
       - 阎罗王众赞叹品第八: dizangjing/8.md
       - 称佛名号品第九: dizangjing/9.md
     - 地藏菩萨本愿经卷上:
       - 校量布施功德缘品第十: dizangjing/10.md
       - 地神护法品第十一: dizangjing/11.md
       - 见闻利益品第十二: dizangjing/12.md
       - 嘱累人天品第十三: dizangjing/13.md
 - 华严经:
     - 世主妙严品第一:
       - 之一: huayanjing/1.md
       - 之二: huayanjing/2.md
       - 之三: huayanjing/3.md
       - 之四: huayanjing/4.md
       - 之五: huayanjing/5.md
     - 如来现相品: huayanjing/6.md
     - 普贤三昧品: huayanjing/7.md
     - 世界成就品: huayanjing/8.md
     - 华藏世界品第五:
       - 之一: huayanjing/9.md
       - 之二: huayanjing/10.md
       - 之三: huayanjing/11.md
     - 毗卢遮那品第六: huayanjing/12.md
     - 如来名号品第七: huayanjing/13.md
     - 四圣谛品第八: huayanjing/14.md
     - 光明觉品第九: huayanjing/15.md
     - 菩萨问明品第十: huayanjing/16.md
     - 净行品第十一: huayanjing/17.md
     - 贤首品第十二:
       - 之一: huayanjing/18.md
       - 之二: huayanjing/19.md
     - 升须弥山顶品第十三: huayanjing/20.md
     - 须弥顶上偈赞第十四: huayanjing/21.md
     - 十住第十五: huayanjing/22.md
     - 梵行品第十六: huayanjing/23.md
     - 初发心功德品第十七: huayanjing/24.md
     - 明法品第十八: huayanjing/25.md
     - 升夜摩天宫品第十九: huayanjing/26.md
     - 夜摩宫中偈赞品第二十: huayanjing/27.md
     - 十行品第二十一:
       - 之一: huayanjing/28.md
       - 之二: huayanjing/29.md
     - 十无尽藏品第二十二: huayanjing/30.md
     - 升兜率天宫品第二十三: huayanjing/31.md
     - 兜率宫中偈赞品第二十四: huayanjing/32.md
     - 十回向品第二十五:
       - 之一: huayanjing/33.md
       - 之二: huayanjing/34.md
       - 之三: huayanjing/35.md
       - 之四: huayanjing/36.md
       - 之五: huayanjing/37.md
       - 之六: huayanjing/38.md
       - 之七: huayanjing/39.md
       - 之八: huayanjing/40.md
       - 之九: huayanjing/41.md
       - 之十: huayanjing/42.md
       - 之十一: huayanjing/43.md
     - 十地品第二十六:
       - 之一: huayanjing/44.md
       - 之二: huayanjing/45.md
       - 之三: huayanjing/46.md
       - 之四: huayanjing/47.md
       - 之五: huayanjing/48.md
       - 之六: huayanjing/49.md
     - 十定品第二十七:
       - 之一: huayanjing/50.md
       - 之二: huayanjing/51.md
       - 之三: huayanjing/52.md
       - 之四: huayanjing/53.md
     - 十通品第二十八: huayanjing/54.md
     - 十忍品第二十九: huayanjing/55.md
     - 阿僧祇品第三十: huayanjing/56.md
     - 寿量品第三十一: huayanjing/57.md
     - 诸菩萨住处品第三十二: huayanjing/58.md
     - 佛不思议法品第三十三:
       - 之一: huayanjing/59.md
       - 之二: huayanjing/60.md
     - 如来十身相海品第三十四: huayanjing/61.md
     - 如来随好光明功德品第三十五: huayanjing/62.md
     - 普贤行品第三十六: huayanjing/63.md
     - 如来出现品第三十七:
       - 之一: huayanjing/64.md
       - 之二: huayanjing/65.md
       - 之三: huayanjing/66.md
     - 离世间品第三十八:
       - 之一: huayanjing/67.md
       - 之二: huayanjing/68.md
       - 之三: huayanjing/69.md
       - 之四: huayanjing/70.md
       - 之五: huayanjing/71.md
       - 之六: huayanjing/72.md
       - 之七: huayanjing/73.md
     - 入法界品第三十九:
       - 之一: huayanjing/74.md
       - 之二: huayanjing/75.md
       - 之三: huayanjing/76.md
       - 之四: huayanjing/77.md
       - 之五: huayanjing/78.md
       - 之六: huayanjing/79.md
       - 之七: huayanjing/80.md
       - 之八: huayanjing/81.md
       - 之九: huayanjing/82.md
       - 之十: huayanjing/83.md
       - 之十一: huayanjing/84.md
       - 之十二: huayanjing/85.md
       - 之十三: huayanjing/86.md
       - 之十四: huayanjing/87.md
       - 之十五: huayanjing/88.md
       - 之十六: huayanjing/89.md
       - 之十七: huayanjing/90.md
       - 之十八: huayanjing/91.md
       - 之十九: huayanjing/92.md
       - 之二十: huayanjing/93.md
       - 之二十一: huayanjing/94.md
 - 维摩诘经:
   - 佛国品第一: weimojing/1.md
   - 善权品第二: weimojing/2.md
   - 弟子品第三: weimojing/3.md
   - 菩萨品第四: weimojing/4.md
   - 诸法言品第五: weimojing/5.md
   - 不思议品第六: weimojing/6.md
   - 观众生品第七: weimojing/7.md
   - 佛道品第八: weimojing/8.md
   - 入不二法门品第九: weimojing/9.md
   - 香积佛品第十: weimojing/10.md
   - 菩萨行品第十一: weimojing/11.md
   - 见阿佛品第十二: weimojing/12.md
   - 法供养品第十三: weimojing/13.md
   - 嘱累品第十四: weimojing/14.md
